CREATE TABLE `ssd`.`ciudad` (
	`idciudad` INT NOT NULL AUTO_INCREMENT ,
	`nombreciudad` VARCHAR(100) NOT NULL,
    `idpais` INT NOT NULL,
	PRIMARY KEY (`idciudad`),
	FOREIGN KEY (`idpais`) REFERENCES pais(idpais)
);

INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (1,'Aachen',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (2,'Albuquerque',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (3,'Anchorage',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (4,'Århus',56);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (5,'Barcelona',202);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (6,'Barquisimeto',236);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (7,'Bérgamo',106);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (8,'Berlín',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (9,'Bern',209);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (10,'Boise',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (11,'Bräcke',210);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (12,'Brandenburg',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (13,'Bruxelles',21);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (14,'Buenos Aires',10);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (15,'Butte',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (16,'Campinas',30);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (17,'Caracas',236);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (18,'Charleroi',21);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (19,'Colchester',229);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (20,'Cork',104);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (21,'Cowes',229);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (22,'Cunewalde',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (23,'Elgin',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (24,'Eugene',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (25,'Frankfurt a.M. ',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (26,'Genève',209);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (27,'Graz',14);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (28,'Helsinki',71);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (29,'I. de Margarita',236);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (30,'Kirkland',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (31,'Köln',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (32,'København',56);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (33,'Lander',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (34,'Leipzig',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (35,'Lille',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (36,'Lisboa',177);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (37,'London',229);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (38,'Luleå',210);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (39,'Lyon',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (40,'Madrid',202);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (41,'Mannheim',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (42,'Marseille',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (43,'México D.F.',142);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (44,'Montréal',38);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (45,'München',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (46,'Münster',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (47,'Nantes',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (48,'Oulu',71);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (49,'Portland',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (50,'Reggio Emilia',106);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (51,'Reims',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (52,'Resende',30);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (53,'Río de Janeiro',30);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (54,'Salzburg',14);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (55,'San Cristóbal',236);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (56,'San Francisco',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (57,'São Paulo',30);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (58,'Seattle',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (59,'Sevilla',202);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (60,'Stavern',165);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (61,'Strasbourg',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (62,'Stuttgart',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (63,'Torino',106);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (64,'Toulouse',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (65,'Tsawassen',38);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (66,'Vancouver',38);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (67,'Walla Walla',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (68,'Warszawa',176);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (69,'París',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (70,'Versailles',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (71,'New Orleans',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (72,'Ann Arbor',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (73,'Tokyo',110);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (74,'Oviedo',202);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (75,'Osaka',110);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (76,'Melbourne',13);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (77,'Manchester',229);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (78,'Göteborg',210);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (79,'Frankfurt',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (80,'Cuxhaven',80);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (81,'Ravenna',106);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (82,'Sandvika',165);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (83,'Londres',229);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (84,'Bend',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (85,'Stockholm',110);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (86,'Boston',230);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (87,'Singapore',195);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (88,'Lyngby',56);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (89,'Zaandam',155);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (90,'Lappeenranta',71);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (91,'Sydney',13);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (92,'Salerno',106);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (93,'Montceau',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (94,'Annecy',72);
INSERT INTO `ciudad` (`idciudad`,`nombreciudad`,`idpais`) VALUES (95,'Ste-Hyacinthe',38);
